In [ ]:
import numpy as np
import pandas as pd

In [15]:
sort_by = ["dgp", "statistic", "method", "n"]
csv_reference= pd.read_csv("results_uz_es/results_uz_es.csv").sort_values(sort_by)
csv_new = pd.read_csv("results_eh_es/results_eh_es.csv").sort_values(sort_by)

In [16]:
csv_reference

,method,nominal_1_sided_coverage,nominal_2_sided_coverage,lower_coverage,upper_coverage,two_sided_coverage,mean_length,median_length,valid_interval_rate,n,dgp,statistic,B,repetitions
21,double,0.975,0.95,0.988,0.992,0.980,1.662338,1.769114,1.0,8,DGPBiNorm-1_1_2.0_0.5_1.0,corr,1000,1000
25,double,0.975,0.95,0.975,0.970,0.945,0.660928,0.656007,1.0,32,DGPBiNorm-1_1_2.0_0.5_1.0,corr,1000,1000
29,double,0.975,0.95,0.982,0.970,0.952,0.311876,0.310331,1.0,128,DGPBiNorm-1_1_2.0_0.5_1.0,corr,1000,1000
20,percentile,0.975,0.95,0.927,0.963,0.890,1.226762,1.282109,1.0,8,DGPBiNorm-1_1_2.0_0.5_1.0,corr,1000,1000
24,percentile,0.975,0.95,0.953,0.961,0.914,0.593838,0.591241,1.0,32,DGPBiNorm-1_1_2.0_0.5_1.0,corr,1000,1000
28,percentile,0.975,0.95,0.977,0.969,0.946,0.301490,0.300686,1.0,128,DGPBiNorm-1_1_2.0_0.5_1.0,corr,1000,1000
7,double,0.975,0.95,0.987,0.931,0.918,1.602932,1.460817,1.0,8,DGPExp_1,mean,1000,1000
9,double,0.975,0.95,0.973,0.972,0.945,0.791517,0.750759,1.0,32,DGPExp_1,mean,1000,1000
17,double,0.975,0.95,0.978,0.974,0.952,0.359783,0.356568,1.0,128,DGPExp_1,mean,1000,1000
6,percentile,0.975,0.95,0.975,0.872,0.847,1.162922,1.083376,1.0,8,DGPExp_1,mean,1000,1000
8,percentile,0.975,0.95,0.977,0.938,0.915,0.665503,0.647543,1.0,32,DGPExp_1,mean,1000,1000
16,percentile,0.975,0.95,0.981,0.965,0.946,0.342556,0.339781,1.0,128,DGPExp_1,mean,1000,1000
15,double,0.975,0.95,0.979,0.975,0.954,1.609814,1.490424,1.0,8,DGPExp_1,median,1000,1000
19,double,0.975,0.95,0.967,0.979,0.946,0.705432,0.680319,1.0,32,DGPExp_1,median,1000,1000
27,double,0.975,0.95,0.973,0.973,0.946,0.352057,0.349074,1.0,128,DGPExp_1,median,1000,1000
14,percentile,0.975,0.95,0.964,0.966,0.930,1.395290,1.312150,1.0,8,DGPExp_1,median,1000,1000
18,percentile,0.975,0.95,0.961,0.975,0.936,0.684892,0.661149,1.0,32,DGPExp_1,median,1000,1000
26,percentile,0.975,0.95,0.972,0.976,0.948,0.349178,0.345933,1.0,128,DGPExp_1,median,1000,1000
1,double,0.975,0.95,0.972,0.973,0.945,1.695435,1.658536,1.0,8,DGPNorm_0_1,mean,1000,1000
5,double,0.975,0.95,0.973,0.974,0.947,0.725978,0.722371,1.0,32,DGPNorm_0_1,mean,1000,1000
11,double,0.975,0.95,0.976,0.962,0.938,0.352617,0.352281,1.0,128,DGPNorm_0_1,mean,1000,1000
0,percentile,0.975,0.95,0.948,0.949,0.897,1.249822,1.235576,1.0,8,DGPNorm_0_1,mean,1000,1000
4,percentile,0.975,0.95,0.968,0.970,0.938,0.680092,0.673639,1.0,32,DGPNorm_0_1,mean,1000,1000
10,percentile,0.975,0.95,0.974,0.958,0.932,0.346234,0.345725,1.0,128,DGPNorm_0_1,mean,1000,1000
3,double,0.975,0.95,0.977,0.970,0.947,1.853614,1.811813,1.0,8,DGPNorm_0_1,median,1000,1000
13,double,0.975,0.95,0.972,0.977,0.949,0.884229,0.874742,1.0,32,DGPNorm_0_1,median,1000,1000
23,double,0.975,0.95,0.977,0.959,0.936,0.436186,0.433241,1.0,128,DGPNorm_0_1,median,1000,1000
2,percentile,0.975,0.95,0.953,0.957,0.910,1.631923,1.566968,1.0,8,DGPNorm_0_1,median,1000,1000
12,percentile,0.975,0.95,0.963,0.975,0.938,0.850592,0.840628,1.0,32,DGPNorm_0_1,median,1000,1000
22,percentile,0.975,0.95,0.978,0.959,0.937,0.432304,0.429080,1.0,128,DGPNorm_0_1,median,1000,1000

In [8]:
csv_new

,method,nominal_1_sided_coverage,nominal_2_sided_coverage,lower_coverage,upper_coverage,two_sided_coverage,mean_length,median_length,valid_interval_rate,n,dgp,statistic,B,repetitions
25,double,0.975,0.95,0.992,0.991,0.983,1.680981,1.781542,1.0,8,DGPBiNorm-1_1_2.0_0.5_1.0,corr,1000,1000
27,double,0.975,0.95,0.978,0.971,0.949,0.656085,0.650048,1.0,32,DGPBiNorm-1_1_2.0_0.5_1.0,corr,1000,1000
29,double,0.975,0.95,0.980,0.983,0.963,0.309898,0.309971,1.0,128,DGPBiNorm-1_1_2.0_0.5_1.0,corr,1000,1000
24,percentile,0.975,0.95,0.941,0.968,0.909,1.250383,1.308233,1.0,8,DGPBiNorm-1_1_2.0_0.5_1.0,corr,1000,1000
26,percentile,0.975,0.95,0.966,0.962,0.928,0.588768,0.588248,1.0,32,DGPBiNorm-1_1_2.0_0.5_1.0,corr,1000,1000
28,percentile,0.975,0.95,0.980,0.976,0.956,0.300942,0.300885,1.0,128,DGPBiNorm-1_1_2.0_0.5_1.0,corr,1000,1000
13,double,0.975,0.95,0.988,0.926,0.914,1.576473,1.440407,1.0,8,DGPExp_1,mean,1000,1000
15,double,0.975,0.95,0.978,0.967,0.945,0.781911,0.730017,1.0,32,DGPExp_1,mean,1000,1000
17,double,0.975,0.95,0.976,0.972,0.948,0.358200,0.354315,1.0,128,DGPExp_1,mean,1000,1000
12,percentile,0.975,0.95,0.977,0.846,0.823,1.142848,1.047192,1.0,8,DGPExp_1,mean,1000,1000
14,percentile,0.975,0.95,0.981,0.937,0.918,0.662392,0.639560,1.0,32,DGPExp_1,mean,1000,1000
16,percentile,0.975,0.95,0.987,0.958,0.945,0.341566,0.339598,1.0,128,DGPExp_1,mean,1000,1000
19,double,0.975,0.95,0.977,0.975,0.952,1.648531,1.535871,1.0,8,DGPExp_1,median,1000,1000
21,double,0.975,0.95,0.974,0.979,0.953,0.712545,0.680041,1.0,32,DGPExp_1,median,1000,1000
23,double,0.975,0.95,0.963,0.969,0.932,0.350932,0.346012,1.0,128,DGPExp_1,median,1000,1000
18,percentile,0.975,0.95,0.958,0.959,0.917,1.405911,1.286317,1.0,8,DGPExp_1,median,1000,1000
20,percentile,0.975,0.95,0.976,0.973,0.949,0.685064,0.652999,1.0,32,DGPExp_1,median,1000,1000
22,percentile,0.975,0.95,0.965,0.968,0.933,0.346667,0.344673,1.0,128,DGPExp_1,median,1000,1000
1,double,0.975,0.95,0.972,0.968,0.940,1.680469,1.666507,1.0,8,DGPNorm_0_1,mean,1000,1000
3,double,0.975,0.95,0.967,0.979,0.946,0.721918,0.717315,1.0,32,DGPNorm_0_1,mean,1000,1000
5,double,0.975,0.95,0.981,0.986,0.967,0.349653,0.348409,1.0,128,DGPNorm_0_1,mean,1000,1000
0,percentile,0.975,0.95,0.947,0.941,0.888,1.232888,1.219378,1.0,8,DGPNorm_0_1,mean,1000,1000
2,percentile,0.975,0.95,0.963,0.966,0.929,0.675490,0.674467,1.0,32,DGPNorm_0_1,mean,1000,1000
4,percentile,0.975,0.95,0.979,0.982,0.961,0.344072,0.344171,1.0,128,DGPNorm_0_1,mean,1000,1000
7,double,0.975,0.95,0.975,0.979,0.954,1.868840,1.835738,1.0,8,DGPNorm_0_1,median,1000,1000
9,double,0.975,0.95,0.980,0.986,0.966,0.883169,0.864807,1.0,32,DGPNorm_0_1,median,1000,1000
11,double,0.975,0.95,0.980,0.977,0.957,0.437433,0.430612,1.0,128,DGPNorm_0_1,median,1000,1000
6,percentile,0.975,0.95,0.966,0.969,0.935,1.638490,1.599602,1.0,8,DGPNorm_0_1,median,1000,1000
8,percentile,0.975,0.95,0.978,0.980,0.958,0.854735,0.840771,1.0,32,DGPNorm_0_1,median,1000,1000
10,percentile,0.975,0.95,0.979,0.976,0.955,0.432904,0.427857,1.0,128,DGPNorm_0_1,median,1000,1000